{\rtf1\ansi\ansicpg936\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 version: "3.7"\
\
services:\
#Mysql Container\
  db:\
    container_name: glpi_db\
    image: mysql:5.7.23\
    command:\
      --default-authentication-plugin=mysql_native_password\
      --character-set-server=utf8mb4\
      --collation-server=utf8mb4_unicode_ci\
      --explicit_defaults_for_timestamp=true\
    restart: always\
    privileged: true\
    environment:\
      - MYSQL_ROOT_PASSWORD=3nvisi0n!\
      - TZ=Asia/Shanghai   \
      - MYSQL_DATABASE=glpidb\
      - MYSQL_USER=glpi_user\
      - MYSQL_PASSWORD=glpi\
    volumes:\
      - /root/web_app_glpi/database:/var/lib/mysql\
    networks:\
      - glpi\
\
#GLPI Container\
  glpi:\
    image: diouxx/glpi\
    container_name : glpi\
    ports:\
      - "8080:80"\
    volumes:\
      - /etc/timezone:/etc/timezone\
      - /etc/localtime:/etc/localtime\
      - /var/www/html/glpi/:/var/www/html/glpi\
    environment:\
      - TIMEZONE=Asia/Shanghai\
    restart: always\
    networks:\
      - glpi\
\
\
networks:\
  glpi:}