version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    privileged: true
    restart: always
    volumes:
      - $pwd/certs:/certs
      - $pwd/html:/usr/share/nginx/html
      - $pwd/nginx.conf:/etc/nginx/nginx.conf
      - $pwd/conf.d:/etc/nginx/conf.d
      - $pwd/logs:/var/log/nginx
    networks:
      - nginx

networks:
  nginx:
