version: '3.7'
services:
  mindoc:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    privileged: true
    restart: always
    volumes:
      - $link/certs:/certs
      - $link/html:/usr/share/nginx/html
      - $link/nginx.conf:/etc/nginx/nginx.conf
      - $link/conf.d:/etc/nginx/conf.d
      - $link/logs:/var/log/nginx
      networks:
      - nginx

networks:
  nginx:
