version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    ports:
      - “9090:9090”
    volumes:
      - /root/docker/web_prometheus/config:/config
      - /root/docker/web_prometheus/data/prometheus:/prometheus/data
    command:
      --config.file=/config/prometheus.yml
      --web.enable-lifecycle

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    ports:
      - “9093:9093”
    volumes:
      - /root/docker/web_prometheus/config:/config
      - /root/docker/web_prometheus/data/alertmanager:/alertmanager/data
    command:
      --config.file=/config/alertmanager.yml

    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - “3000:3000”
    volumes:
      - /root/docker/web_prometheus/config/grafana.ini:/etc/grafana/grafana.ini
      - /root/docker/web_prometheus/data/grafana:/var/lib/grafana
