version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - $pwd/config:/config
      - $pwd/data/prometheus:/prometheus/data
    command:
      --config.file=/config/prometheus.yml
      --web.enable-lifecycle
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - $pwd/config:/config
      - $pwd/data/alertmanager:/alertmanager/data
    command:
      --config.file=/config/alertmanager.yml
    networks:
      - monitor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - $pwd/config/grafana.ini:/etc/grafana/grafana.ini
      - $pwd/data/grafana:/var/lib/grafana
    networks:
      - monitor

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
    command:
      --collector.systemd
      --collector.systemd.unit-whitelist=(docker|sshd).service
    networks:
      - monitor

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    restart: always
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "9080:9080"
    networks:
      - monitor

  dingtalk:
    image: timonwong/prometheus-webhook-dingtalk:latest
    container_name: dingtalk
    hostname: dingtalk
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime
    ports:
      - "8060:8060"
    entrypoint: /bin/prometheus-webhook-dingtalk --ding.profile=webhook1=https://oapi.dingtalk.com/robot/send?access_token=4272393304ea4b432c35c3e03b00d29b7bdd8aef54dd9c42a15c3ac2fd35c009 #注意这部分是没有引号的
    networks:
      - monitor

networks:
  monitor:
