version: '3.7'
services:
  db:
    container_name: db
    image: mysql:5.7
    command:
      --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=true
    restart: always
    privileged: true
    volumes:
      - $pwd/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=3nvisi0n!"
      - "MYSQL_PASSWORD=3nvisi0n!"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
    networks:
      - nextcloudonlyoffice

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - $pwdd/redis/redis:/data
    networks:
      - nextcloudonlyoffice

  app:
    container_name: nextcloud
    image: wonderfall/nextcloud
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 80:8888
    depends_on:
      - db
      - redis
    environment:
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - MEMORY_LIMIT=1G
      - CRON_MEMORY_LIMIT=1024m
      - CRON_PERIOD=2m
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=3nvisi0n!
      - DB_HOST=db:3306
    volumes:
      - $pwdd/nextcloud:/var/www/html
    networks:
      - nextcloudonlyoffice

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - $pwd/document_data:/var/www/onlyoffice/Data
      - $pwd/document_log:/var/log/onlyoffice
    networks:
      - nextcloudonlyoffice

networks:
    nextcloudonlyoffice:

volumes:
  redis:
  mysql_data:
  nextcloud:
  document_data:
  document_log:
