version: '3.7'
services:
  db:
    container_name: db
    image: mysql:5.7
    command:
      --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=true
    restart: always
    privileged: true
    volumes:
      - $pwd/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=3nvisi0n!"
      - "MYSQL_PASSWORD=3nvisi0n!"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
    networks:
      - nextcloudonlyoffice

  app:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '9000'
    depends_on:
      - db
    volumes:
      - $pwd/nextcloud:/var/www/html
    networks:
      - nextcloudonlyoffice

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - $pwd/document_data:/var/www/onlyoffice/Data
      - $pwd/document_log:/var/log/onlyoffice
    networks:
      - nextcloudonlyoffice

  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $pwd/nginx.conf:/etc/nginx/nginx.conf
      - $pwd/app_data:/var/www/html
      - $pwd/conf.d:/etc/nginx/conf.d
    networks:
      - nextcloudonlyoffice

networks:
    nextcloudonlyoffice:

volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
