# 全局配置项
 global:
   resolve_timeout: 5m  #处理超时时间，默认为5min
   smtp_smarthost: 'smtp.163.com:25'  # 邮箱smtp服务器代理
   smtp_from: 'ticket_titans@163.com'  # 发送邮箱名称
   smtp_auth_username: 'ticket_titans@163.com'  # 邮箱名称
   smtp_auth_password: 'zhangjian1986'  #邮箱密码

# 定义模板信心
# templates:
#   - '/etc/alertmanager/templates/*.html'

# 定义路由树信息
 route:
   group_by: ['alertname'] # 报警分组依据
   group_wait: 10s # 最初即第一次等待多久时间发送一组警报的通知
   group_interval: 10s # 在发送新警报前的等待时间
   repeat_interval: 10m # 发送重复警报的周期 对于email配置中，此项不可以设置过低，否则将会由于邮件发送太多频繁，被smtp服务器拒绝
   receiver: 'slack' # 发送警报的接收者的名称，以下receivers name的名称
# 定义警报接收者信息
 receivers:
#   - name: 'email' # 警报
#     email_configs: # 邮箱配置
#     - to: 'zhang.jian@titans-systems.cn'  # 接收警报的email配置
   - name: 'slack'
     email_configs: # 邮箱配置
       - to: 'zhang.jian@titans-systems.cn'  # 接收警报的email配置
     slack_configs:
       - api_url: 'https://hooks.slack.com/services/XXXX' # slack api 地址
         channel: '#test'
         text: 'click here'
         title: "{{.CommonAnnotations.summary}}"
         title_link: "{{.CommonAnnotations.link}}"
         color: "{{.CommonAnnotations.color}}"
     webhook_configs:
       - url: 'http://192.168.0.251:8060/dingtalk/webhook1/send'
         send_resolved: true
#     html: '{{ template "test.html" . }}' # 设定邮箱的内容模板
#     headers: { Subject: "[WARN] 报警邮件"} # 接收邮件的标题
#     webhook_configs: # webhook配置
#     - url: 'http://127.0.0.1:5001'
