global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'monitor'

# 普罗米修斯 规则文件
rule_files:
  - "rules/*_rules.yml"
  - "rules/*_alerts.yml"

# prometheus自身的Alert功能是根据我们配置的 规则文件 进行触发的，但是它并没有告警发邮件的功能，发送邮件的这件事儿是由 Alertmanager来做的
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "127.0.0.1:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label \`job=<job_name>\` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['127.0.0.1:9090']

  # 后期追加mysql监控
  - job_name: 'uat-mysql'
    static_configs:
      - targets: ['127.0.0.1:9104']

  # 后期追加机器监控
  - job_name: 'node'
    static_configs:
      - targets: ['127.0.0.1:9100']

  - job_name: 'docker'
    static_configs:
      - targets: ['127.0.0.1:8080']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['127.0.0.1:9093']
